### ISSUE TITLE
Rails app freeze again, one of the tubesocks thread died

### ISSUE THREAD

**Issue by nateless** [ngauthier/tubesock#42] opened 2015-02-24 11:22 UTC
Still trying to figure out what's happening. I dump all threads backtraces each 15 seconds, and after another crash go this.

`#<Thread:0x007f6630fbed28@/home/service/app/shared/bundle/ruby/2.2.0/bundler/gems/tubesock-debaacc0012d/lib/tubesock.rb:84 dead>`. This is ping thread. No other errors on the log regarding this thread.

Then for other clients it's just started to throw:

```
Errno::EPIPE (Broken pipe):
  app/controllers/stream_controller.rb:9:in `index'
```

Where line 9 in our app is `hijack do |tubesock|`.

**Comment by ngauthier** [comment] 2015-03-02 13:11
Do you have the full backtrace so we can figure out where in tubesock the broken pipe was raised?

**Comment by nateless** [comment] 2015-03-04 13:19
The funny thing is there's no full backtrace, that's all I have in production.log.

**Comment by ngauthier** [comment] 2015-03-04 13:26
Try editing `config/initializers/backtrace_silencers.rb` to remove the comment on `remove_silencers!` that will enable backtraces for gems and rails and stuff.

**Comment by dovestyle** [comment] 2015-10-01 23:19
Hi, I'm also receiving an Errno::EPIPE (Broken pipe) error.

After initial research, many people seemed to relate it to the DB connection pool, but I raised my pool size to 100 just to test, and I never went over about 50 connections. The error still happened.

The biggest problem I'm having with this error is that it is inconsistent. I get it at random times, but only after the server has been up for a good while.

Here's the full backtrace for your enjoyment. Line 20 of events_controller is simply the `hijack do |sock|`

    F, [2015-10-01T23:02:24.174434 #89722] FATAL -- : 
    Errno::EPIPE (Broken pipe):
      tubesock (0.2.5) lib/tubesock.rb:27:in `write'
      tubesock (0.2.5) lib/tubesock.rb:27:in `hijack'
      tubesock (0.2.5) lib/tubesock/hijack.rb:30:in `hijack'
      app/controllers/events_controller.rb:20:in `index'
      actionpack (4.2.4) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
      actionpack (4.2.4) lib/abstract_controller/base.rb:198:in `process_action'
      actionpack (4.2.4) lib/action_controller/metal/rendering.rb:10:in `process_action'
      actionpack (4.2.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
      activesupport (4.2.4) lib/active_support/callbacks.rb:117:in `call'
      activesupport (4.2.4) lib/active_support/callbacks.rb:117:in `call'
      activesupport (4.2.4) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
      activesupport (4.2.4) lib/active_support/callbacks.rb:505:in `call'
      activesupport (4.2.4) lib/active_support/callbacks.rb:505:in `call'
      activesupport (4.2.4) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
      activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
      activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
      actionpack (4.2.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
      actionpack (4.2.4) lib/action_controller/metal/rescue.rb:29:in `process_action'
      actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
      activesupport (4.2.4) lib/active_support/notifications.rb:164:in `block in instrument'
      activesupport (4.2.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      activesupport (4.2.4) lib/active_support/notifications.rb:164:in `instrument'
      actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
      actionpack (4.2.4) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
      activerecord (4.2.4) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
      actionpack (4.2.4) lib/abstract_controller/base.rb:137:in `process'
      actionview (4.2.4) lib/action_view/rendering.rb:30:in `process'
      actionpack (4.2.4) lib/action_controller/metal.rb:196:in `dispatch'
      actionpack (4.2.4) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
      actionpack (4.2.4) lib/action_controller/metal.rb:237:in `block in action'
      actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:76:in `call'
      actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
      actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:45:in `serve'
      actionpack (4.2.4) lib/action_dispatch/journey/router.rb:43:in `block in serve'
      actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `each'
      actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `serve'
      actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:821:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
      omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
      omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
      warden (1.2.3) lib/warden/manager.rb:34:in `catch'
      warden (1.2.3) lib/warden/manager.rb:34:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.4) lib/rack/etag.rb:24:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.4) lib/rack/head.rb:13:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.4) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.4) lib/action_dispatch/middleware/flash.rb:260:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
      rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:560:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      activerecord (4.2.4) lib/active_record/query_cache.rb:36:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
      activesupport (4.2.4) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
      activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
      activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
      actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.4) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
      railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
      activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
      activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
      activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
      railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      request_store (1.2.0) lib/request_store/middleware.rb:8:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.4) lib/rack/runtime.rb:18:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
      newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
      railties (4.2.4) lib/rails/engine.rb:518:in `call'
      railties (4.2.4) lib/rails/application.rb:165:in `call'
      puma (2.13.4) lib/puma/configuration.rb:78:in `call'
      puma (2.13.4) lib/puma/server.rb:541:in `handle_request'
      puma (2.13.4) lib/puma/server.rb:388:in `process_client'
      puma (2.13.4) lib/puma/server.rb:270:in `block in run'
      puma (2.13.4) lib/puma/thread_pool.rb:106:in `call'
      puma (2.13.4) lib/puma/thread_pool.rb:106:in `block in spawn_thread'

**Comment by depili** [comment] 2015-11-17 15:16
Just a wild guess, but this might be a timing issue caused by the connection closing during the handover with Rack::Hijack. In such case just rescuing the error should be enough.

**Comment by dovestyle** [comment] 2015-11-17 19:42
@depili Indeed. It looks like that's what @ngauthier started doing in the master branch. Once I pulled that down, the errors cleared up.

**Closed** 2020-09-09 02:23 UTC
