### ISSUE TITLE
Close is not called if message handlers crash

### ISSUE THREAD

**Issue by Burgestrand** [ngauthier/tubesock#44] opened 2015-03-13 13:46 UTC
Hi!

Looking at https://github.com/ngauthier/tubesock/blob/e2ae989e2c6bbfbcd53571a055ccbc07cc06a7df/lib/tubesock.rb#L68

Since there is no exception handling in this thread, if any of the handlers raise an error the `close` call will never happen. For example, if a handler crashes `close` will not be called, and all cleanup associated with it will not happen.

Maybe wrapping this code in the following would be a good idea?

```ruby
begin
  …
ensure
  close
end
```

**Comment by ngauthier** [comment] 2015-03-13 13:50
Yeah sounds good!

**Comment by teddythetwig** [comment] 2015-06-30 09:19
I decided to take a crack at this and realized it was more interesting than it appeared from the surface. The question is, what is the expected behavior when a handler crashes? Here is what I was thinking are the options:
1. When a handler crashes, the socket is immediately closed
2. When a handler crashes, we rescue the error and call the rest of the message handlers for the frame, then close the socket
3. When a handler crashes, we rescue the error, and continue on our merry way as if nothing happened

IMO option 3 makes the most sense, at least in the context of how I am using it.

What do yall think?

**Comment by Burgestrand** [comment] 2015-06-30 09:46
1 and 3 sounds OK to me. 2 is harder for me to think of a use case where it is appropriate.

Whichever is chosen, I feel errors should not disappear into the void. There should be some place where errors are bubbled up to, so that they may reported for later fixing. Perhaps an on_error handler, called for just about any error during the lifetime of a connection?

**Comment by teddythetwig** [comment] 2015-06-30 10:05
I was thinking something similar to this. Sometimes I just need to be able to address the cause of the error without everything exploding in my face.

Lets give this a shot.

**Comment by teddythetwig** [comment] 2015-06-30 10:16
Sorry for my terrible amends :p

So what this will do is allow the user to register an onerror handler, and when a message handler errors, all the error handlers will be called, and then the socket will close.

This can easily be modified to work more like option 3, although honestly I'm not sure which way would be better.

What behavior are you all expecting?

**Comment by Burgestrand** [comment] 2015-06-30 10:38
I have three thoughts!

1. What happens if an error handler crashes? (I'm thinking just ignore it, let it bubble and allow abort_on_exception handle it)
2. Should the socket close on error be optional, instead of always closing? (If you want that behavior, an error handler could do that?)
3. #close is still not guaranteed to be called when the thread exits, if e.g. an open handler or each_frame raises an error, the socket will not be closed.

**Comment by teddythetwig** [comment] 2015-06-30 11:13
1. I was thinking the same, it is definitely possible that someone writes faulty error handlers, but at some point the user needs to take responsibility.

2.  That would be easy to implement, I'll add that

3. Oops, you are absolutely right

**Comment by teddythetwig** [comment] 2015-06-30 12:17
Alright, I've added some more tests. I think this covers all of the cases. I had to manually exit the thread instead of relying on #abort_on_exception

**Comment by teddythetwig** [comment] 2015-06-30 14:27
@Burgestrand thanks a ton for the comments, it always helps to have a second pair of eyes. Hoooopefully this should be closer to what we are looking for in the behavior.

Right now, the onerror handlers will only fire when there is an error in an onmessage handler.

The socket will correctly close whenever the onopen handler raises an error, but the onerror handler will not fire.

**Comment by depili** [comment] 2015-06-30 16:14
I'll be soon converting my stuff from websocket-rails to tubesock and the behavior that would make the most sense for me would be to allow on_error callbacks, as I would use them to update slideshow display states as invalid.

When it comes to possibly crashing error handlers I would like to see that error bubble up, as debugging a crashing error handler that gets silently eaten is always a huge pain.

I would also prefer a clear behavior when it comes to closing the socket and always closing on error makes perfect sense to me and would pretty much mirror how things are on the browser side. Leaving hanging zombie-sockets around could also become an issue on larger setups.

If you can't be sure that the socket gets closed on error then some kind of ping-pong might be in order to cull the stale connections?

**Comment by ngauthier** [comment] 2015-07-02 17:55
I've merged @teddythetwig's PR. Does this work for everyone?

**Closed** 2015-07-02 17:55 UTC

**Comment by depili** [comment] 2015-07-02 17:59
Seems like a solid solution and nice way to hook app specific handlers, should work for me nicely.

**Comment by ngauthier** [comment] 2015-07-02 18:00
Great. I'll close this issue, but @Burgestrand feel free to reopen if you have any troubles! Thanks @teddythetwig!
