### ISSUE TITLE
Problem with Passenger Enterprise 4.0.14

### ISSUE THREAD

**Issue by fokcep** [ngauthier/tubesock#10] opened 2013-09-24 13:30 UTC
Just wondering if someone had issues running tubesock with the Passenger Enterprise Server. Could be nothing to do with tubesock at all. It supposed to run ok. But getting a long delay when calling the following bit of code from tubesock:

```rails
def self.hijack(env)
  .......    
  handshake.from_rack env
  .......
end
```

it takes around 50 seconds to execute this method and eventually it fails to get WS connection.

Dump of env['rack.hijack']

Proc:0x00000004505060@/opt/passenger/passenger-enterprise-server-4.0.14/lib/phusion_passenger/rack/thread_handler_extension.rb:53 (lambda)

any ideas?

Thanks

**Comment by akshayrawat** [comment] 2015-01-21 11:04
I can confirm this is still a problem in development env where `cache_classes = false`. 

Removing `Rack::Lock` in development environment fixes it. But I think doing that might cause inconsistent class reloading, as then the requests wouldn't be run under a mutex, causing class reloading to not always be seen by all threads (or be inconsistent in some other way.).

Passenger Enterprise - 4.0.49,  Tubesock - 0.2.5, Websocket - 1.2.1, `Rails 4.1.8`.

**Comment by FooBarWidget** [comment] 2015-02-02 21:16
Phusion Passenger author here. I've found out the cause of the Rack::Lock problems. It boils down to a difference in Rack socket hijacking behavior bewteen Passenger and Puma.

The story begins with Rack::Lock. The idea of Rack::Lock is to ensure requests are handled serially, in order to prevent code reloading from breaking during development. This is because code reloading and multithreading are fundamentally incompatible. So Rack::Lock grabs the mutex before the request is processed. Rack::Lock releases the mutex in one of two cases:

 1. If the request finishes with a normal body, then Rack::Lock releases the mutex immediately.
 2. If the request finishes with a body that responds to #close, e.g. a File object, then Rack::Lock releases the mutex when #close is called on the body.

Passenger never calls #close on the body when the socket is hijacked, and so the the Rack::Lock mutex is never released, giving rise to the "recursive locking" problem. Puma does, and so Rack::Lock happens to work.

I've looked into how other servers behave. Thin calls #close on the body even after hijacking, though Tubesock doesn't work properly on Thin. Unicorn does not, and so it would suffer from the same problem that Passenger experiences, but Tubesock doesn't work on Unicorn for a totally different reason (namely that in Unicorn, the hijacked IO object is a Rack::Lint::HijackWrapper and Tubesock doesn't like that).

I've also looked into what the Rack specification says, but it's extremely vague. Here is the relevant paragraph:

> Response (after headers)
>
> It is also possible to hijack a response after the status and headers have been sent. [...] Servers must ignore the body part of the response tuple when the rack.hijack response API is in use.

So the specification says that servers must ignore the body object when hijacked. But does it mean servers must ignore the body upon a partial hijack (i.e. after headers are sent)? Or does it mean that servers must ALSO ignore the body upon a full hijack? I have no idea, and it's something I need to ask the Rack mailing list.

**Comment by FooBarWidget** [comment] 2015-02-02 21:27
My Rack mailing list question: https://groups.google.com/forum/#!topic/rack-devel/afpYGMoFP0c

**Comment by FooBarWidget** [comment] 2015-02-02 21:43
So you can close this issue now. The Rack::Lock problem must be fixed in either Passenger+Unicorn or Puma+Thin+Rack::Lock, not in Tubesock. Passenger seems to otherwise work fine with Tubesock.

**Comment by ngauthier** [comment] 2015-02-02 22:05
Thanks for all the context!

Also, I am completely in support of adding server-specific plugins for tubesock if it comes to that (even though like you say this should be done via the Rack spec). We can follow in Rails's footsteps and have an abstract adapter that follows Rack, then have other adapters subclass from it and implement server-specific differences. Then someone can simply require tubesock then require tubesock/passenger for example.

**Closed by ngauthier** 2015-02-02 22:05 UTC

**Comment by FooBarWidget** [comment] 2015-06-03 14:13
I've made a change in Passenger 5.0.9. We now emulate Puma behavior; that is, we close the body even when the socket is hijacked. That should fix the Rack::Lock problems.

Unfortunately, I never heard back from the Rack guys about what behavior is considered official.
